//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchByLucene.Service.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DataResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SearchByLucene.Service.Data.DataResource", typeof(DataResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU;Produto;Fabricante;CodFabricante;CodMercadocar;CodReferencia;Montadora;Veiculo;Modelo;Versao;Motor;Valvula;Cilindrada;AnoInicio;AnoFim
        ///167278;Filtro de Ar FIAT PALIO (2010 - 2017) - MANN HUMMEL C370011;MANN HUMMEL;C370011;;;FIAT;PALIO;;;;16V;1.6;2010;2017
        ///168511;Amortecedor Traseiro HONDA ACCORD (2005 - 2007) - COFAP GB27653;COFAP;GB27653;;GB27653 | COFAP, 2915100G1081 | HONDA, 341331 | KYB, 341369 | KYB, 0079.0015.0707 | MERCADOCAR;HONDA;ACCORD;;;;24V;3.0;2005;2007
        ///168755;Terminal de Direção RENAULT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MCSmallData {
            get {
                return ResourceManager.GetString("MCSmallData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU;Veiculo;Modelo;Versao;Motor;Valvula;Cilindrada;AnoInicio;AnoFim;Produto
        ///1;Corsa  Hatch;Wind  ;G1;EFI  ;;1.0;1994;2002;Automóvel
        ///2;Corsa  Hatch;Wind Super ;G1;EFI  ;;1.0;1995;1995;Automóvel
        ///3;Corsa  Hatch;Wind  ;G1;MPFI  ;;1.0;1996;2002;Automóvel
        ///4;Corsa  Hatch;Wind Champ Série especial;G1;EFI  ;;1.0;1995;1995;Automóvel
        ///5;Corsa  Hatch;Super  ;G1;MPFI  ;8;1.0;1996;2000;Automóvel
        ///6;Corsa  Hatch;Super  ;G1;MPFI  ;16;1.0;1999;2002;Automóvel
        ///7;Corsa  Hatch;GL  ;G1;EFI ;;1.4;1995;1999;Automóvel
        ///8;Corsa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MyData {
            get {
                return ResourceManager.GetString("MyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product;Synonym
        ///Água Desmineralizada;Água de Bateria, Solução de Bateria, Solução Desmineralizada, Solução para Radiador
        ///Alça de Teto;Alca Externa Cabine, Alca Frontal Cabine, Alca Teto, Pega Mao Capo, Puta que Pariu, Pqp
        ///Anel Sincronizador;Sincronizado Anel
        ///Anti-Chamas;Espuma do Anti Chama, Espuma Filtro Ar, Respiro de Oleo, Separador de Oleo, Válvula Pcv
        ///Aplique de Maçaneta;Capa para Maçaneta
        ///Barra Axial;Axial, Articulação da Caixa, Barra Axial, Braço Axial
        ///Aspirador de Pó;Aspirador de Líquido
        ///Aut [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SynonymsBasic {
            get {
                return ResourceManager.GetString("SynonymsBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product;Synonym
        ///Acabamento da Moldura;moldura decorativa, revestimento de moldura, detalhe de acabamento
        ///Acabamento de Roda;acabamento de roda, calota, capa de roda
        ///Adaptador de Soquete;conversor de encaixe, adaptador para encaixe de soquete, redutor de encaixe
        ///Adaptador para Antena;conector de antena, adaptador de sinal, conversor de antena
        ///Adaptador para Ipod;adaptador para dispositivos apple, adaptador de conexão para ipod, adaptador de áudio para ipod
        ///Adaptador para Soquete;conversor de encaixe, a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SynonymsNames {
            get {
                return ResourceManager.GetString("SynonymsNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product;Synonym
        ///Abraçadeira do Para-lama;grampo de para-lama, presilha do para-lama, suporte do para-lama;sim
        ///Acabamento Aplique do Para-choque;friso do para-choque, moldura do para-choque, revestimento do para-choque;sim
        ///Acabamento da Cabine;acabamento interno, forração da cabine, revestimento da cabine;sim
        ///Acabamento da Churrasqueira;acabamento do capô, detalhe do capô, embelezador do capô;sim
        ///Acabamento da Coluna;acabamento da coluna de porta, guarnição da coluna, revestimento da coluna;sim
        ///Acabame [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SynonymsNamesV2 {
            get {
                return ResourceManager.GetString("SynonymsNamesV2", resourceCulture);
            }
        }
    }
}
